SELECT 
	K.TABLE_NAME t, 
	K.COLUMN_NAME c, 
	K.REFERENCED_TABLE_NAME tref, 
	K.REFERENCED_COLUMN_NAME cref, 
	C.IS_NULLABLE cnull, 
	JTYPE(C.DATA_TYPE) ctype
	-- C.COLUMN_KEY, 
	-- C.EXTRA
FROM 	
	INFORMATION_SCHEMA.KEY_COLUMN_USAGE K  
	INNER JOIN 
	INFORMATION_SCHEMA.COLUMNS C 
	ON K.TABLE_NAME = C.TABLE_NAME AND K.COLUMN_NAME = C.COLUMN_NAME AND C.TABLE_SCHEMA = K.TABLE_SCHEMA
WHERE K.REFERENCED_TABLE_NAME IS NOT NULL
AND K.TABLE_NAME = "&table" AND K.TABLE_SCHEMA = "&db"
